Refactor lua loader
XuJiandong/ckb-lua pull request #27
Opened 2022-09-13 04:25 UTC by contrun

This PR removes a gigantic macro, adds a function to get intermediate result and renames a few functions.

2022-09-13 06:09 UTC, XuJiandong commented
Merge changes from the master branch and the CI will work.

2022-09-14 01:09 UTC, XuJiandong requested changes

2022-09-14 01:09 UTC, XuJiandong commented on lua-loader/lua-ckb.c
> +    /* We have allocated a buffer with a size larger than what is needed */
Why not just malloc the smaller size one? The realloc operation is not necessary.

2022-09-14 01:13 UTC, XuJiandong commented
Add a test case: loop 10000 times; Every time, it reads 100K data. Then watch if it has a memory leak issue or not.

2022-09-14 01:57 UTC, XuJiandong requested changes

2022-09-14 02:07 UTC, XuJiandong requested changes

2022-09-14 02:07 UTC, XuJiandong commented on lua-loader/lua-ckb.c
> +        ret = call_syscall(f, NULL);
When the length is fetched, the `offset` should be passed in. Different `offset` get different lengths.

2022-09-14 02:49 UTC, contrun commented on lua-loader/lua-ckb.c
> +    /* We have allocated a buffer with a size larger than what is needed */
The realloc is only necessary when the lua script passed a length argument and the actual data size is less than that length. realloc only shrink the memory space size.

2022-09-14 02:50 UTC, contrun commented on lua-loader/lua-ckb.c
> +    /* We have allocated a buffer with a size larger than what is needed */
I think if the lua script explicitly passed a length, we should alloc that number of memory.

2022-09-14 02:51 UTC, contrun commented on lua-loader/lua-ckb.c
> +    uint8_t *buf = malloc(buflen);
I think I can set a maximum for the size of memory. But if the data is really that large, the lua script itself should pass a length argument.

2022-09-14 02:54 UTC, contrun commented on lua-loader/lua-ckb.c
> +        ret = call_syscall(f, NULL);
The offset argument is bundled in the struct syscall_function_t f. It is indeed passed.

2022-09-14 03:04 UTC, XuJiandong commented on lua-loader/lua-ckb.c
> +    /* We have allocated a buffer with a size larger than what is needed */
The shrink operation is not necessary and wrong. What if the underlying data is very large (e.g. 300k) but we only fetch part of it (e.g. 1k)?

2022-09-14 03:32 UTC, XuJiandong commented
Add a test case: witness has 500k data. Use load_witness to fetch part of it (e.g. 100 bytes).

2022-09-14 07:08 UTC, merged